In [1]:
# Loading packages
import numpy as np
from pulp import *

In [2]:
# Problem Information
fvariablecosts = np.array([[3,5,8,12,10,11],
                           [6,7,10,12,8,10],
                           [5,3,8,10,12,10],
                           [7,6,7,10,9,5],
                           [10,8,5,8,6,5],
                           [12,6,4,7,5,4],
                           [7,10,6,6,8,3],
                           [5,6,9,4,4,7],
                           [8,10,7,5,4,6],
                           [10,12,8,3,4,6]])

fixedcosts = [1750000,1800000,3000000,2250000,1500000,1000000]
capacity = [75,50,120,100,60,50]
demand=[25,15,20,10,15,15,25,20,30,20]

In [5]:
# Case 1
model1 = LpProblem("Capacitated facility location problem",LpMinimize)

x = LpVariable.dicts("x",((i, j) for i in range(10) for j in range(6)),lowBound=0,cat='Continuous')
y = LpVariable.dicts("y",((j) for j in range(6)),cat='Binary')

for i in range(10):
    model1 += pulp.lpSum([x[i,j] for j in range(6)]) == 1
for j in range(6):
    model1 += pulp.lpSum([demand[i]*x[i,j]  for i in range(10)]) <= y[j]*capacity[j]

# Objective Function
model1 += pulp.lpSum([demand[i]*fvariablecosts[i,j] * x[i,j] for i in range(10) for j in range(6)]) + pulp.lpSum([fixedcosts[j]*y[j] for j in range(6)])
model1.solve()
pulp.LpStatus[model1.status]
X = np.zeros(10*6)
Y = np.zeros(6)
i = 0
for variable in model1.variables():
    #print ("{} = {}".format(variable.name, variable.varValue))
    if i<6*10:
        X[i]= variable.varValue
    else:
        Y[i-60] = variable.varValue
    i += 1
X = np.reshape(X,(10,6))
print(model1)
print('X =\n', X)
print('Y =', Y)
print ('Optimal objective value:',value(model1.objective))

Capacitated facility location problem:
MINIMIZE
75*x_(0,_0) + 125*x_(0,_1) + 200*x_(0,_2) + 300*x_(0,_3) + 250*x_(0,_4) + 275*x_(0,_5) + 90*x_(1,_0) + 105*x_(1,_1) + 150*x_(1,_2) + 180*x_(1,_3) + 120*x_(1,_4) + 150*x_(1,_5) + 100*x_(2,_0) + 60*x_(2,_1) + 160*x_(2,_2) + 200*x_(2,_3) + 240*x_(2,_4) + 200*x_(2,_5) + 70*x_(3,_0) + 60*x_(3,_1) + 70*x_(3,_2) + 100*x_(3,_3) + 90*x_(3,_4) + 50*x_(3,_5) + 150*x_(4,_0) + 120*x_(4,_1) + 75*x_(4,_2) + 120*x_(4,_3) + 90*x_(4,_4) + 75*x_(4,_5) + 180*x_(5,_0) + 90*x_(5,_1) + 60*x_(5,_2) + 105*x_(5,_3) + 75*x_(5,_4) + 60*x_(5,_5) + 175*x_(6,_0) + 250*x_(6,_1) + 150*x_(6,_2) + 150*x_(6,_3) + 200*x_(6,_4) + 75*x_(6,_5) + 100*x_(7,_0) + 120*x_(7,_1) + 180*x_(7,_2) + 80*x_(7,_3) + 80*x_(7,_4) + 140*x_(7,_5) + 240*x_(8,_0) + 300*x_(8,_1) + 210*x_(8,_2) + 150*x_(8,_3) + 120*x_(8,_4) + 180*x_(8,_5) + 200*x_(9,_0) + 240*x_(9,_1) + 160*x_(9,_2) + 60*x_(9,_3) + 80*x_(9,_4) + 120*x_(9,_5) + 1750000*y_0 + 1800000*y_1 + 3000000*y_2 + 2250000*y_3 + 1500000*y_4 + 10

In [4]:
# Case 2: single sourcing
model2 = LpProblem("Capacitated facility location problem",LpMinimize)
x = LpVariable.dicts("x",((i, j) for i in range(10) for j in range(6)),cat='Binary')
y = LpVariable.dicts("y",((j) for j in range(6)),cat='Binary')

for i in range(10):
    model2 += pulp.lpSum([x[i,j] for j in range(6)]) == 1
for j in range(6):
    model2 += pulp.lpSum([demand[i]*x[i,j]  for i in range(10)]) <= y[j]*capacity[j]

# Objective Function
model2 += pulp.lpSum([demand[i]*fvariablecosts[i,j] * x[i,j] for i in range(10) for j in range(6)]) + pulp.lpSum([fixedcosts[j]*y[j] for j in range(6)])
model2.solve()
pulp.LpStatus[model2.status]
X = np.zeros(10*6)
Y = np.zeros(6)
i = 0
for variable in model2.variables():
    #print ("{} = {}".format(variable.name, variable.varValue))
    if i<6*10:
        X[i]= variable.varValue
    else:
        Y[i-60] = variable.varValue
    i += 1
X = np.reshape(X,(10,6))
print('X =\n', X)
print('Y =', Y)
print ('Optimal objective value:',value(model2.objective))

X =
 [[0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]
Y = [0. 0. 0. 1. 1. 1.]
Optimal objective value: 4751135.0


In [5]:
# Case 3: single sourcing + no warehouse is allowed to work with more than 3 customers
for j in range(6):
    model2 += pulp.lpSum([x[i,j]  for i in range(10)]) <= 3
    
model2.solve()
pulp.LpStatus[model2.status]
X = np.zeros(10*6)
Y = np.zeros(6)
i = 0
for variable in model2.variables():
    #print ("{} = {}".format(variable.name, variable.varValue))
    if i<6*10:
        X[i]= variable.varValue
    else:
        Y[i-60] = variable.varValue
    i += 1
X = np.reshape(X,(10,6))
print('X =\n', X)
print('Y =', Y)
print ('Optimal objective value:',value(model2.objective))

X =
 [[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]]
Y = [1. 1. 0. 0. 1. 1.]
Optimal objective value: 6050815.0
